## Import Libraries 

In [1]:
import pandas as pd
import numpy as np


## 0.7mm-Bearing-Fault

In [2]:
# 3-Phase-current-0.7mm-bearing-fault

# 0.7inner-100watt
inner_07_100watt = pd.read_csv('0.7inner-100watt.csv')

# 0.7outer-100watt
outer_07_100watt = pd.read_csv('0.7outer-100watt.csv')


### Drop the columns and selecting   0.7inner-100watt and 0.7outer-100watt



In [3]:
# select Current-A from 07inner_100watt
current_A_07inner_100watt = inner_07_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_07inner_100watt

Current-A
0           2.3309
1           2.3309
2           2.3309
3           2.3309
4           2.3309
...            ...
143343      2.7936
143344      2.7936
143345      2.7936
143346      2.7936
143347      2.7936

[143348 rows x 1 columns]

In [4]:
outer_07_100watt.head()

Time Stamp   Current-A   Current-B   Current-C
0   14:18:51      2.7973      1.3724      3.1929
1   14:18:51      2.7973      1.3724      3.1929
2   14:18:51      2.7973      1.3724      3.1929
3   14:18:51      2.7973      1.3724      3.1929
4   14:18:51      2.7973      1.3724      3.1929

In [5]:
current_A_07inner_100watt_100k = current_A_07inner_100watt[0:100000]
current_A_07inner_100watt_100k

Current-A
0          2.3309
1          2.3309
2          2.3309
3          2.3309
4          2.3309
...           ...
99995      2.9817
99996      2.9817
99997      2.9817
99998      2.9817
99999      2.9817

[100000 rows x 1 columns]

In [6]:
r100_c1k_current_A_07inner_100watt = current_A_07inner_100watt_100k.values.reshape(100,1000)
r100_c1k_current_A_07inner_100watt

array([[2.3309, 2.3309, 2.3309, ..., 2.7228, 2.7228, 2.7228],
       [2.7228, 2.7228, 2.7228, ..., 2.9524, 2.9524, 2.9524],
       [2.9524, 2.9524, 2.9524, ..., 2.1111, 2.1111, 2.1111],
       ...,
       [2.4127, 2.4127, 2.4127, ..., 2.7668, 2.7668, 2.7668],
       [2.7668, 2.7668, 2.7668, ..., 2.011 , 2.011 , 2.011 ],
       [2.011 , 2.011 , 2.011 , ..., 2.9817, 2.9817, 2.9817]])

In [7]:
df_current_A_07inner_100watt = pd.DataFrame(r100_c1k_current_A_07inner_100watt)
df_current_A_07inner_100watt

0       1       2       3       4       5       6       7       8    \
0   2.3309  2.3309  2.3309  2.3309  2.3309  2.3309  2.3309  2.3309  2.3309   
1   2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228   
2   2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524   
3   2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111   
4   2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.9194  2.9194  2.9194  2.9194  2.9194  2.9194  2.9194  2.9194  2.9194   
96  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990   
97  2.4127  2.4127  2.4127  2.4127  2.4127  2.4127  2.4127  2.4127  2.4127   
98  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668   
99  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110   

       9    ...     990     991     992     993     994     995     996  \
0   2.3309  ...  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228   
1   2.7228  ...  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524   
2   2.9524  ...  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111   
3   2.1111  ...  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282   
4   2.1282  ...  2.9805  2.9805  2.9805  2.9805  2.9805  3.0024  3.0024   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.9194  ...  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990   
96  2.1990  ...  2.5043  2.5043  2.5043  2.5043  2.5043  2.5043  2.5043   
97  2.4127  ...  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668   
98  2.7668  ...  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110   
99  2.0110  ...  3.0171  2.9817  2.9817  2.9817  2.9817  2.9817  2.9817   

       997     998     999  
0   2.7228  2.7228  2.7228  
1   2.9524  2.9524  2.9524  
2   2.1111  2.1111  2.1111  
3   2.1282  2.1282  2.1282  
4   3.0024  3.0024  3.0024  
..     ...     ...     ...  
95  2.1990  2.1990  2.1990  
96  2.5043  2.5043  2.5043  
97  2.7668  2.7668  2.7668  
98  2.0110  2.0110  2.0110  
99  2.9817  2.9817  2.9817  

[100 rows x 1000 columns]

In [8]:
df_current_A_07inner_100watt['Status'] = '0.7_Inner_Bearing_Unhealthy'

In [9]:
df_current_A_07inner_100watt

0       1       2       3       4       5       6       7       8  \
0   2.3309  2.3309  2.3309  2.3309  2.3309  2.3309  2.3309  2.3309  2.3309   
1   2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228   
2   2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524   
3   2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111   
4   2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.9194  2.9194  2.9194  2.9194  2.9194  2.9194  2.9194  2.9194  2.9194   
96  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990   
97  2.4127  2.4127  2.4127  2.4127  2.4127  2.4127  2.4127  2.4127  2.4127   
98  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668   
99  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110   

         9  ...     991     992     993     994     995     996     997  \
0   2.3309  ...  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228   
1   2.7228  ...  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524   
2   2.9524  ...  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111   
3   2.1111  ...  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282   
4   2.1282  ...  2.9805  2.9805  2.9805  2.9805  3.0024  3.0024  3.0024   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.9194  ...  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990  2.1990   
96  2.1990  ...  2.5043  2.5043  2.5043  2.5043  2.5043  2.5043  2.5043   
97  2.4127  ...  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668  2.7668   
98  2.7668  ...  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110   
99  2.0110  ...  2.9817  2.9817  2.9817  2.9817  2.9817  2.9817  2.9817   

       998     999                       Status  
0   2.7228  2.7228  0.7_Inner_Bearing_Unhealthy  
1   2.9524  2.9524  0.7_Inner_Bearing_Unhealthy  
2   2.1111  2.1111  0.7_Inner_Bearing_Unhealthy  
3   2.1282  2.1282  0.7_Inner_Bearing_Unhealthy  
4   3.0024  3.0024  0.7_Inner_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.1990  2.1990  0.7_Inner_Bearing_Unhealthy  
96  2.5043  2.5043  0.7_Inner_Bearing_Unhealthy  
97  2.7668  2.7668  0.7_Inner_Bearing_Unhealthy  
98  2.0110  2.0110  0.7_Inner_Bearing_Unhealthy  
99  2.9817  2.9817  0.7_Inner_Bearing_Unhealthy  

[100 rows x 1001 columns]

## Select Current-A from 07outer_100watt

In [10]:

current_A_07outer_100watt = outer_07_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_07outer_100watt

Current-A
0           2.7973
1           2.7973
2           2.7973
3           2.7973
4           2.7973
...            ...
130110      2.0904
130111      2.0904
130112      2.0904
130113      2.0904
130114      2.0904

[130115 rows x 1 columns]

In [11]:
current_A_07outer_100watt_100k = current_A_07outer_100watt[0:100000]
current_A_07outer_100watt_100k

Current-A
0          2.7973
1          2.7973
2          2.7973
3          2.7973
4          2.7973
...           ...
99995      2.4982
99996      2.4982
99997      2.4982
99998      2.4982
99999      2.4982

[100000 rows x 1 columns]

In [12]:
r100_c1k_df_current_A_07outer_100watt = current_A_07outer_100watt_100k.values.reshape(100,1000)
r100_c1k_df_current_A_07outer_100watt

array([[2.7973, 2.7973, 2.7973, ..., 2.0122, 2.0122, 2.0122],
       [2.0122, 2.0122, 2.0122, ..., 3.0415, 3.0415, 3.0415],
       [3.0415, 3.0415, 3.0415, ..., 2.2283, 2.2283, 2.2283],
       ...,
       [2.9438, 2.9438, 2.9438, ..., 2.1502, 2.1502, 2.1502],
       [2.1502, 2.1502, 2.1502, ..., 2.6239, 2.6239, 2.6239],
       [2.6239, 2.6239, 2.6239, ..., 2.4982, 2.4982, 2.4982]])

In [13]:
df_current_A_07outer_100watt = pd.DataFrame(r100_c1k_df_current_A_07outer_100watt)

In [14]:
df_current_A_07outer_100watt['Status'] = '0.7_Outer_Bearing_Unhealthy'

In [15]:
df_current_A_07outer_100watt

0       1       2       3       4       5       6       7       8  \
0   2.7973  2.7973  2.7973  2.7973  2.7973  2.7973  2.7973  2.7973  2.7973   
1   2.0122  2.0122  2.0122  2.0122  2.0391  2.0391  2.0391  2.0391  2.0391   
2   3.0415  3.0415  3.0415  3.0415  3.0415  3.0415  3.0415  3.0415  3.0415   
3   2.2283  2.2283  2.2283  2.2283  2.2283  2.2283  2.2283  2.1661  2.1661   
4   2.4835  2.4835  2.4835  2.4835  2.4835  2.4835  2.4835  2.4835  2.4835   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  3.0354  3.0354  3.0354  3.0354  3.0354  3.0354  3.0354  3.0354  3.0354   
96  1.9939  1.9939  1.9939  1.9939  1.9939  1.9939  1.9939  1.9939  1.9939   
97  2.9438  2.9438  2.9438  2.9438  2.9438  2.9438  2.9438  2.9023  2.9023   
98  2.1502  2.1502  2.1502  2.1502  2.1502  2.1502  2.1502  2.1502  2.1502   
99  2.6239  2.6239  2.6239  2.6239  2.6239  2.6239  2.6239  2.6239  2.6239   

         9  ...     991     992     993     994     995     996     997  \
0   2.7973  ...  2.0122  2.0122  2.0122  2.0122  2.0122  2.0122  2.0122   
1   2.0391  ...  3.0415  3.0415  3.0415  3.0415  3.0415  3.0415  3.0415   
2   3.0415  ...  2.2283  2.2283  2.2283  2.2283  2.2283  2.2283  2.2283   
3   2.1661  ...  2.4835  2.4835  2.4835  2.4835  2.4835  2.4835  2.4835   
4   2.4835  ...  2.8620  2.8620  2.8620  2.8620  2.8620  2.8620  2.8620   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  3.0354  ...  1.9939  1.9939  1.9939  1.9939  1.9939  1.9939  1.9939   
96  1.9939  ...  2.9438  2.9438  2.9438  2.9438  2.9438  2.9438  2.9438   
97  2.9023  ...  2.1502  2.1502  2.1502  2.1502  2.1502  2.1502  2.1502   
98  2.1502  ...  2.6239  2.6239  2.6239  2.6239  2.6239  2.6239  2.6239   
99  2.6239  ...  2.4982  2.4982  2.4982  2.4982  2.4982  2.4982  2.4982   

       998     999                       Status  
0   2.0122  2.0122  0.7_Outer_Bearing_Unhealthy  
1   3.0415  3.0415  0.7_Outer_Bearing_Unhealthy  
2   2.2283  2.2283  0.7_Outer_Bearing_Unhealthy  
3   2.4835  2.4835  0.7_Outer_Bearing_Unhealthy  
4   2.8620  2.8620  0.7_Outer_Bearing_Unhealthy  
..     ...     ...                          ...  
95  1.9939  1.9939  0.7_Outer_Bearing_Unhealthy  
96  2.9438  2.9438  0.7_Outer_Bearing_Unhealthy  
97  2.1502  2.1502  0.7_Outer_Bearing_Unhealthy  
98  2.6239  2.6239  0.7_Outer_Bearing_Unhealthy  
99  2.4982  2.4982  0.7_Outer_Bearing_Unhealthy  

[100 rows x 1001 columns]

## 0.9mm-bearing-fault

In [16]:
# 0.9inner-100watt
inner_09_100watt = pd.read_csv('0.9inner-100watt.csv')

# 0.9outer-100watt
outer_09_100watt = pd.read_csv('0.9outer-100watt.csv')

## Drop the columns and selecting the Current-A column from  0.9inner-100watt and 0.9outer-100watt 

In [17]:
# select Current-A from 0.9inner_100watt
current_A_09inner_100watt = inner_09_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_09inner_100watt

Current-A
0           3.0281
1           3.0281
2           3.0281
3           3.0281
4           3.0281
...            ...
152411      2.9255
152412      2.9255
152413      2.9255
152414      2.9255
152415      2.9255

[152416 rows x 1 columns]

In [18]:
current_A_09inner_100watt_100K = current_A_09inner_100watt[0:100000]
current_A_09inner_100watt_100K

Current-A
0          3.0281
1          3.0281
2          3.0281
3          3.0281
4          3.0281
...           ...
99995      3.0134
99996      3.0134
99997      3.0134
99998      3.0134
99999      3.0134

[100000 rows x 1 columns]

In [19]:
r100_c1k_current_A_09inner_100watt = current_A_09inner_100watt_100K.values.reshape(100,1000)
r100_c1k_current_A_09inner_100watt

array([[3.0281, 3.0281, 3.0281, ..., 3.0488, 3.0488, 3.0488],
       [3.0488, 3.0488, 3.0488, ..., 2.2955, 2.2955, 2.2955],
       [2.2955, 2.2955, 2.2955, ..., 2.1648, 2.1648, 2.1648],
       ...,
       [2.2125, 2.2125, 2.2125, ..., 2.0159, 2.0159, 2.0159],
       [2.0159, 2.0159, 2.0159, ..., 2.5788, 2.5788, 2.5788],
       [2.5788, 2.5788, 2.5788, ..., 3.0134, 3.0134, 3.0134]])

In [20]:
df_current_A_09inner_100watt = pd.DataFrame(r100_c1k_current_A_09inner_100watt)


In [21]:
df_current_A_09inner_100watt['Status'] = '0.9_Inner_Bearing_Unhealthy'

In [22]:
df_current_A_09inner_100watt

0       1       2       3       4       5       6       7       8  \
0   3.0281  3.0281  3.0281  3.0281  3.0281  3.0281  3.0281  3.0281  3.0281   
1   3.0488  3.0488  3.0488  3.0488  3.0488  3.0488  3.0488  3.0488  3.0488   
2   2.2955  2.2955  2.2955  2.2955  2.2955  2.2955  2.2955  2.2955  2.2955   
3   2.1648  2.1648  2.1648  2.1648  2.1648  2.1648  2.1648  2.1648  2.1648   
4   3.0635  3.0635  3.0635  3.0635  3.0635  3.0635  3.0635  3.0635  3.0635   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  3.0098  3.0098  3.0098  3.0098  3.0098  3.0098  3.0098  3.0098  3.0098   
96  2.8352  2.8352  2.8352  2.8352  2.8352  2.8352  2.8352  2.8352  2.8352   
97  2.2125  2.2125  2.2125  2.2125  2.2125  2.2125  2.2125  2.2125  2.2125   
98  2.0159  2.0159  2.0159  2.0159  2.0159  2.0159  2.0159  2.0159  2.0159   
99  2.5788  2.5788  2.5788  2.5788  2.5788  2.5788  2.5788  2.5788  2.5788   

         9  ...     991     992     993     994     995     996     997  \
0   3.0281  ...  3.0488  3.0488  3.0488  3.0488  3.0488  3.0488  3.0488   
1   3.0488  ...  2.2955  2.2955  2.2955  2.2955  2.2955  2.2955  2.2955   
2   2.2955  ...  2.1648  2.1648  2.1648  2.1648  2.1648  2.1648  2.1648   
3   2.1648  ...  3.0635  3.0635  3.0635  3.0635  3.0635  3.0635  3.0635   
4   3.0635  ...  2.0403  2.0403  2.0403  2.0403  2.0403  2.0403  2.0403   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  3.0098  ...  2.8352  2.8352  2.8352  2.8352  2.8352  2.8352  2.8352   
96  2.8352  ...  2.2125  2.2125  2.2125  2.2125  2.2125  2.2125  2.2125   
97  2.2125  ...  2.0159  2.0159  2.0159  2.0159  2.0159  2.0159  2.0159   
98  2.0159  ...  2.5788  2.5788  2.5788  2.5788  2.5788  2.5788  2.5788   
99  2.5788  ...  3.0134  3.0134  3.0134  3.0134  3.0134  3.0134  3.0134   

       998     999                       Status  
0   3.0488  3.0488  0.9_Inner_Bearing_Unhealthy  
1   2.2955  2.2955  0.9_Inner_Bearing_Unhealthy  
2   2.1648  2.1648  0.9_Inner_Bearing_Unhealthy  
3   3.0635  3.0635  0.9_Inner_Bearing_Unhealthy  
4   2.0403  2.0403  0.9_Inner_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.8352  2.8352  0.9_Inner_Bearing_Unhealthy  
96  2.2125  2.2125  0.9_Inner_Bearing_Unhealthy  
97  2.0159  2.0159  0.9_Inner_Bearing_Unhealthy  
98  2.5788  2.5788  0.9_Inner_Bearing_Unhealthy  
99  3.0134  3.0134  0.9_Inner_Bearing_Unhealthy  

[100 rows x 1001 columns]

In [23]:
outer_09_100watt.head()

Time Stamp   Current-A   Current-B   Current-C
0   11:18:50      3.7314       1.917      1.8523
1   11:18:50      3.7314       1.917      1.8523
2   11:18:50      3.7314       1.917      1.8523
3   11:18:50      3.7314       1.917      1.8523
4   11:18:50      3.7314       1.917      1.8523

In [24]:
# select Current-A from 09outer_100watt
current_A_09outer_100watt = outer_09_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_09outer_100watt

Current-A
0           3.7314
1           3.7314
2           3.7314
3           3.7314
4           3.7314
...            ...
140555      1.9389
140556      1.9389
140557      1.9389
140558      1.9389
140559      1.9389

[140560 rows x 1 columns]

In [25]:
current_A_09outer_100watt_100K = current_A_09outer_100watt[0:100000]
current_A_09outer_100watt_100K

Current-A
0          3.7314
1          3.7314
2          3.7314
3          3.7314
4          3.7314
...           ...
99995      2.9927
99996      2.9927
99997      2.9927
99998      2.9927
99999      2.9927

[100000 rows x 1 columns]

In [26]:
r100_c1k_current_A_09outer_100watt = current_A_09outer_100watt_100K.values.reshape(100,1000)
r100_c1k_current_A_09outer_100watt

array([[3.7314, 3.7314, 3.7314, ..., 1.9609, 1.9609, 1.9609],
       [1.9609, 1.9609, 1.9609, ..., 2.9084, 2.9084, 2.9084],
       [2.9084, 2.9084, 2.9548, ..., 2.6129, 2.6129, 2.6129],
       ...,
       [2.3663, 2.3663, 2.3663, ..., 2.8474, 2.8474, 2.8474],
       [2.8474, 2.8474, 2.8474, ..., 2.0623, 2.0623, 2.0623],
       [2.0623, 2.0623, 2.0623, ..., 2.9927, 2.9927, 2.9927]])

In [27]:
df_current_A_09outer_100watt = pd.DataFrame(r100_c1k_current_A_09outer_100watt)

In [28]:
df_current_A_09outer_100watt['Status'] = '0.9_Outer_Bearing_Unhealthy'

In [29]:
df_current_A_09outer_100watt

0       1       2       3       4       5       6       7       8  \
0   3.7314  3.7314  3.7314  3.7314  3.7314  3.7314  3.6935  3.6935  3.6935   
1   1.9609  1.9609  1.9609  1.9609  1.9609  1.9609  1.9609  1.9609  1.9609   
2   2.9084  2.9084  2.9548  2.9548  2.9548  2.9548  2.9548  2.9548  2.9548   
3   2.6129  2.6129  2.6129  2.6129  2.6129  2.6129  2.6129  2.6129  2.6129   
4   1.9524  1.9524  1.9524  1.9524  1.9524  1.9524  1.9524  1.9524  1.9524   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.7766  2.7766  2.7766  2.7766  2.7766  2.8181  2.8181  2.8181  2.8181   
96  2.4151  2.4151  2.4151  2.4151  2.4151  2.4151  2.4151  2.4151  2.4151   
97  2.3663  2.3663  2.3663  2.3663  2.3663  2.3663  2.3663  2.3663  2.3663   
98  2.8474  2.8474  2.8474  2.8474  2.8474  2.8474  2.8474  2.8474  2.8474   
99  2.0623  2.0623  2.0623  2.0623  2.0623  2.0623  2.0623  2.0623  2.0623   

         9  ...     991     992     993     994     995     996     997  \
0   3.6935  ...  1.9609  1.9609  1.9609  1.9609  1.9609  1.9609  1.9609   
1   1.9609  ...  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084   
2   2.9548  ...  2.6129  2.6129  2.6129  2.6129  2.6129  2.6129  2.6129   
3   2.6129  ...  1.9524  1.9524  1.9524  1.9524  1.9524  1.9524  1.9524   
4   1.9524  ...  3.0733  3.0733  3.0733  3.0733  3.0733  3.0733  3.0733   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.8181  ...  2.4151  2.4151  2.4151  2.4151  2.4151  2.4151  2.4151   
96  2.4151  ...  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552   
97  2.3663  ...  2.8474  2.8474  2.8474  2.8474  2.8474  2.8474  2.8474   
98  2.8474  ...  2.0623  2.0623  2.0623  2.0623  2.0623  2.0623  2.0623   
99  2.0623  ...  2.9927  2.9927  2.9927  2.9927  2.9927  2.9927  2.9927   

       998     999                       Status  
0   1.9609  1.9609  0.9_Outer_Bearing_Unhealthy  
1   2.9084  2.9084  0.9_Outer_Bearing_Unhealthy  
2   2.6129  2.6129  0.9_Outer_Bearing_Unhealthy  
3   1.9524  1.9524  0.9_Outer_Bearing_Unhealthy  
4   3.0733  3.0733  0.9_Outer_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.4151  2.4151  0.9_Outer_Bearing_Unhealthy  
96  2.2552  2.2552  0.9_Outer_Bearing_Unhealthy  
97  2.8474  2.8474  0.9_Outer_Bearing_Unhealthy  
98  2.0623  2.0623  0.9_Outer_Bearing_Unhealthy  
99  2.9927  2.9927  0.9_Outer_Bearing_Unhealthy  

[100 rows x 1001 columns]

## 1.1mm-bearing-fault

In [30]:
# 1.1inner-100watt
inner_11_100watt = pd.read_csv('1.1inner-100watt.csv')

# 1.1outer-100watt
outer_11_100watt = pd.read_csv('1.1outer-100watt.csv')

## Drop the columns and selecting the Current-A column from 1.1inner-100watt and 1.1outer-100watt 

In [31]:
# select Current-A from 1.1inner_100watt
current_A_11inner_100watt = inner_11_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_11inner_100watt

Current-A
0           3.0745
1           3.0745
2           3.0745
3           3.0745
4           3.0745
...            ...
136046      2.1538
136047      2.1538
136048      2.1538
136049      2.1538
136050      2.1538

[136051 rows x 1 columns]

In [32]:
current_A_11inner_100watt_100K = current_A_11inner_100watt[0:100000]
current_A_11inner_100watt_100K

Current-A
0          3.0745
1          3.0745
2          3.0745
3          3.0745
4          3.0745
...           ...
99995      2.8852
99996      2.8852
99997      2.8852
99998      2.8852
99999      2.8852

[100000 rows x 1 columns]

In [33]:
r100_c1k_current_A_11inner_100watt = current_A_11inner_100watt_100K.values.reshape(100,1000)
r100_c1k_current_A_11inner_100watt

array([[3.0745, 3.0745, 3.0745, ..., 2.4994, 2.4994, 2.4994],
       [2.4994, 2.4994, 2.4994, ..., 1.9463, 1.9463, 1.9463],
       [1.9463, 1.9463, 1.9463, ..., 2.1441, 2.1441, 2.1441],
       ...,
       [2.2332, 2.2332, 2.2332, ..., 2.8632, 2.8632, 2.8632],
       [2.8632, 2.8632, 2.8632, ..., 2.0867, 2.0867, 2.0867],
       [2.0867, 2.0867, 2.0867, ..., 2.8852, 2.8852, 2.8852]])

In [34]:
df_current_A_11inner_100watt = pd.DataFrame(r100_c1k_current_A_11inner_100watt)

In [35]:
df_current_A_11inner_100watt['Status'] = '1.1_Inner_Bearing_Unhealthy'

In [36]:
df_current_A_11inner_100watt

0       1       2       3       4       5       6       7       8  \
0   3.0745  3.0745  3.0745  3.0745  3.0745  3.0745  3.0745  3.0745  3.0745   
1   2.4994  2.4994  2.4994  2.4994  2.4994  2.4994  2.4994  2.4994  2.4994   
2   1.9463  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463   
3   2.1441  2.1441  2.1441  2.1441  2.1685  2.1685  2.1685  2.1685  2.1685   
4   2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.5873  2.5873  2.5873  2.5873  2.5873  2.5873  2.5873  2.5873  2.5873   
96  2.6508  2.6508  2.6508  2.6508  2.6508  2.6508  2.6508  2.6508  2.6508   
97  2.2332  2.2332  2.2332  2.2332  2.2332  2.2332  2.2332  2.2332  2.2332   
98  2.8632  2.8632  2.8632  2.8120  2.8120  2.8120  2.8120  2.8120  2.8120   
99  2.0867  2.0867  2.0867  2.0867  2.0867  2.0867  2.0867  2.0867  2.0867   

         9  ...     991     992     993     994     995     996     997  \
0   3.0745  ...  2.5397  2.5397  2.5397  2.5397  2.5397  2.5397  2.4994   
1   2.4994  ...  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463   
2   1.9463  ...  2.1441  2.1441  2.1441  2.1441  2.1441  2.1441  2.1441   
3   2.1685  ...  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084   
4   2.9084  ...  2.9231  2.9231  2.9231  2.9231  2.9231  2.9231  2.9231   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.5873  ...  2.6508  2.6508  2.6508  2.6508  2.6508  2.6508  2.6508   
96  2.6508  ...  2.1734  2.1734  2.2332  2.2332  2.2332  2.2332  2.2332   
97  2.2332  ...  2.8632  2.8632  2.8632  2.8632  2.8632  2.8632  2.8632   
98  2.8120  ...  2.0867  2.0867  2.0867  2.0867  2.0867  2.0867  2.0867   
99  2.0867  ...  2.9414  2.9414  2.8852  2.8852  2.8852  2.8852  2.8852   

       998     999                       Status  
0   2.4994  2.4994  1.1_Inner_Bearing_Unhealthy  
1   1.9463  1.9463  1.1_Inner_Bearing_Unhealthy  
2   2.1441  2.1441  1.1_Inner_Bearing_Unhealthy  
3   2.9084  2.9084  1.1_Inner_Bearing_Unhealthy  
4   2.9231  2.9231  1.1_Inner_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.6508  2.6508  1.1_Inner_Bearing_Unhealthy  
96  2.2332  2.2332  1.1_Inner_Bearing_Unhealthy  
97  2.8632  2.8632  1.1_Inner_Bearing_Unhealthy  
98  2.0867  2.0867  1.1_Inner_Bearing_Unhealthy  
99  2.8852  2.8852  1.1_Inner_Bearing_Unhealthy  

[100 rows x 1001 columns]

In [37]:
df_current_A_11inner_100watt.head()

0       1       2       3       4       5       6       7       8  \
0  3.0745  3.0745  3.0745  3.0745  3.0745  3.0745  3.0745  3.0745  3.0745   
1  2.4994  2.4994  2.4994  2.4994  2.4994  2.4994  2.4994  2.4994  2.4994   
2  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463   
3  2.1441  2.1441  2.1441  2.1441  2.1685  2.1685  2.1685  2.1685  2.1685   
4  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084   

        9  ...     991     992     993     994     995     996     997  \
0  3.0745  ...  2.5397  2.5397  2.5397  2.5397  2.5397  2.5397  2.4994   
1  2.4994  ...  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463   
2  1.9463  ...  2.1441  2.1441  2.1441  2.1441  2.1441  2.1441  2.1441   
3  2.1685  ...  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084   
4  2.9084  ...  2.9231  2.9231  2.9231  2.9231  2.9231  2.9231  2.9231   

      998     999                       Status  
0  2.4994  2.4994  1.1_Inner_Bearing_Unhealthy  
1  1.9463  1.9463  1.1_Inner_Bearing_Unhealthy  
2  2.1441  2.1441  1.1_Inner_Bearing_Unhealthy  
3  2.9084  2.9084  1.1_Inner_Bearing_Unhealthy  
4  2.9231  2.9231  1.1_Inner_Bearing_Unhealthy  

[5 rows x 1001 columns]

In [38]:
# select Current-A from 1.1outer_100watt
current_A_11outer_100watt = outer_11_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_11outer_100watt

Current-A
0           3.0403
1           3.0403
2           3.0403
3           3.0403
4           3.0403
...            ...
135653      1.9792
135654      1.9792
135655      1.9792
135656      1.9792
135657      1.9792

[135658 rows x 1 columns]

In [39]:
current_A_11outer_100watt_100K = current_A_11outer_100watt[0:100000]
current_A_11outer_100watt_100K

Current-A
0          3.0403
1          3.0403
2          3.0403
3          3.0403
4          3.0403
...           ...
99995      2.4505
99996      2.4505
99997      2.4505
99998      2.4505
99999      2.4505

[100000 rows x 1 columns]

In [40]:
r100_c1k_current_A_11outer_100watt = current_A_11outer_100watt_100K.values.reshape(100,1000)
r100_c1k_current_A_11outer_100watt

array([[3.0403, 3.0403, 3.0403, ..., 2.9316, 2.9316, 2.9316],
       [2.9316, 2.9316, 2.9316, ..., 2.8034, 2.8034, 2.8034],
       [2.8034, 2.8034, 2.8034, ..., 2.0085, 2.0085, 2.0085],
       ...,
       [2.0598, 2.0598, 2.0598, ..., 1.978 , 1.978 , 1.978 ],
       [1.978 , 1.978 , 1.978 , ..., 2.1941, 2.1941, 2.1941],
       [2.1941, 2.1941, 2.1941, ..., 2.4505, 2.4505, 2.4505]])

In [41]:
df_current_A_11outer_100watt = pd.DataFrame(r100_c1k_current_A_11outer_100watt)

In [42]:
df_current_A_11outer_100watt['Status'] = '1.1_Outer_Bearing_Unhealthy'

In [43]:
df_current_A_11outer_100watt

0       1       2       3       4       5       6       7       8  \
0   3.0403  3.0403  3.0403  3.0403  3.0403  3.0403  3.0403  3.0403  3.0403   
1   2.9316  2.9316  2.9316  2.9316  2.9316  2.9316  2.9316  2.9316  2.9316   
2   2.8034  2.8034  2.8034  2.8034  2.8034  2.8034  2.8034  2.7582  2.7582   
3   2.0085  2.0085  2.0085  2.0085  2.0085  2.0085  2.0085  2.0085  2.0085   
4   2.2564  2.2564  2.2564  2.2564  2.2564  2.2564  2.2564  2.2564  2.2564   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.8852  2.8852  2.8852  2.8852  2.8852  2.8852  2.8852  2.8852  2.8852   
96  2.4176  2.4176  2.4176  2.4176  2.4176  2.4176  2.4176  2.4176  2.4176   
97  2.0598  2.0598  2.0598  2.0598  2.0598  2.0598  2.0598  2.0598  2.0598   
98  1.9780  1.9780  1.9780  1.9780  1.9780  1.9780  1.9780  1.9780  1.9780   
99  2.1941  2.1941  2.1941  2.1941  2.1941  2.1941  2.2125  2.2125  2.2125   

         9  ...     991     992     993     994     995     996     997  \
0   3.0403  ...  2.9145  2.9145  2.9145  2.9145  2.9145  2.9145  2.9316   
1   2.9316  ...  2.8034  2.8034  2.8034  2.8034  2.8034  2.8034  2.8034   
2   2.7582  ...  2.0269  2.0085  2.0085  2.0085  2.0085  2.0085  2.0085   
3   2.0085  ...  2.2564  2.2564  2.2564  2.2564  2.2564  2.2564  2.2564   
4   2.2564  ...  2.9841  2.9841  2.9841  2.9841  2.9841  2.9841  2.9841   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.8559  ...  2.4457  2.4457  2.4457  2.4176  2.4176  2.4176  2.4176   
96  2.4176  ...  2.0598  2.0598  2.0598  2.0598  2.0598  2.0598  2.0598   
97  2.0598  ...  1.9780  1.9780  1.9780  1.9780  1.9780  1.9780  1.9780   
98  1.9780  ...  2.1941  2.1941  2.1941  2.1941  2.1941  2.1941  2.1941   
99  2.2125  ...  2.4505  2.4505  2.4505  2.4505  2.4505  2.4505  2.4505   

       998     999                       Status  
0   2.9316  2.9316  1.1_Outer_Bearing_Unhealthy  
1   2.8034  2.8034  1.1_Outer_Bearing_Unhealthy  
2   2.0085  2.0085  1.1_Outer_Bearing_Unhealthy  
3   2.2564  2.2564  1.1_Outer_Bearing_Unhealthy  
4   2.9841  2.9841  1.1_Outer_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.4176  2.4176  1.1_Outer_Bearing_Unhealthy  
96  2.0598  2.0598  1.1_Outer_Bearing_Unhealthy  
97  1.9780  1.9780  1.1_Outer_Bearing_Unhealthy  
98  2.1941  2.1941  1.1_Outer_Bearing_Unhealthy  
99  2.4505  2.4505  1.1_Outer_Bearing_Unhealthy  

[100 rows x 1001 columns]

## 1.3mm-bearing-fault

In [44]:
# 1.3inner-100watt
inner_13_100watt = pd.read_csv('1.3inner-100watt.csv')

# 1.3outer-100watt
outer_13_100watt = pd.read_csv('1.3outer-100watt.csv')

### Drop the columns and selecting the Current-A column from 1.3inner-100watt and 1.3outer-100watt 

In [45]:
# select Current-A from 1.3outer_100watt
current_A_13inner_100watt = inner_13_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_13inner_100watt

Current-A
0           2.3724
1           2.3724
2           2.3724
3           2.3724
4           2.3724
...            ...
143268      2.6740
143269      2.6740
143270      2.6740
143271      2.6740
143272      2.6740

[143273 rows x 1 columns]

In [46]:
current_A_13inner_100watt_100k = current_A_13inner_100watt[0:100000]
current_A_13inner_100watt_100k

Current-A
0          2.3724
1          2.3724
2          2.3724
3          2.3724
4          2.3724
...           ...
99995      2.9988
99996      2.9988
99997      2.9988
99998      2.9988
99999      2.9988

[100000 rows x 1 columns]

In [47]:
r100_c1k_current_A_13inner_100watt = current_A_13inner_100watt_100k.values.reshape(100,1000)
r100_c1k_current_A_13inner_100watt

array([[2.3724, 2.3724, 2.3724, ..., 2.1282, 2.1282, 2.1282],
       [2.1282, 2.1282, 2.1282, ..., 1.9585, 1.9585, 1.9585],
       [1.9585, 1.9585, 1.9585, ..., 2.685 , 2.685 , 2.685 ],
       ...,
       [2.4225, 2.4225, 2.4225, ..., 2.7704, 2.7704, 2.7704],
       [2.7704, 2.7704, 2.7704, ..., 3.033 , 3.033 , 3.033 ],
       [3.033 , 3.033 , 3.033 , ..., 2.9988, 2.9988, 2.9988]])

In [48]:
df_current_A_13inner_100watt = pd.DataFrame(r100_c1k_current_A_13inner_100watt)

In [49]:
df_current_A_13inner_100watt['Status'] = '1.3_Inner_Bearing_Unhealthy'

In [50]:
df_current_A_13inner_100watt

0       1       2       3       4       5       6       7       8  \
0   2.3724  2.3724  2.3724  2.3724  2.3724  2.3724  2.3724  2.3724  2.3724   
1   2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282   
2   1.9585  1.9585  1.9585  1.9585  1.9585  1.9585  1.9585  1.9829  1.9829   
3   2.6850  2.6850  2.6850  2.6850  2.6850  2.6850  2.6850  2.6850  2.6850   
4   3.0842  3.0842  3.0842  3.0842  3.0842  3.0842  3.0842  3.0842  3.0842   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  1.9536  1.9536  1.9536  1.9536  1.9536  1.9536  1.9536  1.9536  1.9536   
96  2.0635  2.0635  2.0635  2.0635  2.0635  2.0635  2.0635  2.0635  2.0635   
97  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225   
98  2.7704  2.7704  2.7704  2.7704  2.7704  2.7704  2.7704  2.7704  2.7704   
99  3.0330  3.0330  3.0330  3.0330  3.0330  3.0330  3.0330  3.0330  3.0330   

         9  ...     991     992     993     994     995     996     997  \
0   2.3724  ...  2.1502  2.1502  2.1282  2.1282  2.1282  2.1282  2.1282   
1   2.1282  ...  1.9585  1.9585  1.9585  1.9585  1.9585  1.9585  1.9585   
2   1.9829  ...  2.6361  2.6850  2.6850  2.6850  2.6850  2.6850  2.6850   
3   2.6850  ...  3.0842  3.0842  3.0842  3.0842  3.0842  3.0842  3.0842   
4   3.0842  ...  2.5556  2.5556  2.5556  2.5556  2.5556  2.5556  2.5556   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  1.9536  ...  2.0635  2.0635  2.0635  2.0635  2.0635  2.0635  2.0635   
96  2.0635  ...  2.4005  2.4005  2.4225  2.4225  2.4225  2.4225  2.4225   
97  2.4225  ...  2.7704  2.7704  2.7704  2.7704  2.7704  2.7704  2.7704   
98  2.7704  ...  3.0256  3.0256  3.0256  3.0256  3.0256  3.0330  3.0330   
99  3.0330  ...  2.9988  2.9988  2.9988  2.9988  2.9988  2.9988  2.9988   

       998     999                       Status  
0   2.1282  2.1282  1.3_Inner_Bearing_Unhealthy  
1   1.9585  1.9585  1.3_Inner_Bearing_Unhealthy  
2   2.6850  2.6850  1.3_Inner_Bearing_Unhealthy  
3   3.0842  3.0842  1.3_Inner_Bearing_Unhealthy  
4   2.5556  2.5556  1.3_Inner_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.0635  2.0635  1.3_Inner_Bearing_Unhealthy  
96  2.4225  2.4225  1.3_Inner_Bearing_Unhealthy  
97  2.7704  2.7704  1.3_Inner_Bearing_Unhealthy  
98  3.0330  3.0330  1.3_Inner_Bearing_Unhealthy  
99  2.9988  2.9988  1.3_Inner_Bearing_Unhealthy  

[100 rows x 1001 columns]

In [51]:
# select Current-A from 1.3outer_100watt
current_A_13outer_100watt = outer_13_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_13outer_100watt

Current-A
0           1.8462
1           1.8462
2           1.8462
3           1.8462
4           1.9328
...            ...
132551      2.8974
132552      2.8974
132553      2.8974
132554      2.8974
132555      2.8974

[132556 rows x 1 columns]

In [52]:
current_A_13outer_100watt_100K = current_A_13outer_100watt[0:100000]
current_A_13outer_100watt_100K

Current-A
0          1.8462
1          1.8462
2          1.8462
3          1.8462
4          1.9328
...           ...
99995      2.6874
99996      2.6874
99997      2.6874
99998      2.6874
99999      2.7656

[100000 rows x 1 columns]

In [53]:
r100_c1k_current_A_13outer_100watt = current_A_13outer_100watt_100K.values.reshape(100,1000)
r100_c1k_current_A_13outer_100watt

array([[1.8462, 1.8462, 1.8462, ..., 2.2271, 2.2271, 2.2271],
       [2.2271, 2.2271, 2.2271, ..., 2.9866, 2.9866, 2.9866],
       [2.9866, 2.9866, 2.9866, ..., 2.6374, 2.6374, 2.6374],
       ...,
       [2.4225, 2.4225, 2.4225, ..., 2.9023, 2.9023, 2.9023],
       [2.9023, 2.9023, 2.9023, ..., 1.9597, 1.9597, 1.9597],
       [1.9597, 1.9597, 1.9597, ..., 2.6874, 2.6874, 2.7656]])

In [54]:
df_current_A_13outer_100watt = pd.DataFrame(r100_c1k_current_A_13outer_100watt )

In [55]:
df_current_A_13outer_100watt ['Status'] = '1.3_Outer_Bearing_Unhealthy'

In [56]:
df_current_A_13outer_100watt

0       1       2       3       4       5       6       7       8  \
0   1.8462  1.8462  1.8462  1.8462  1.9328  1.9328  1.9328  1.9328  1.9328   
1   2.2271  2.2271  2.2271  2.2271  2.2271  2.2271  2.2271  2.2271  2.2271   
2   2.9866  2.9866  2.9866  2.9866  2.9866  2.9866  2.9866  3.0000  3.0000   
3   2.6374  2.6374  2.6374  2.6374  2.6374  2.6374  2.6374  2.6374  2.6374   
4   1.9280  1.9280  1.9280  1.9280  1.9280  1.9280  1.9280  1.9280  1.9280   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.9695  2.9695  2.9695  2.9695  2.9695  2.9695  2.9963  2.9963  2.9963   
96  2.1905  2.1905  2.1905  2.1905  2.1905  2.1905  2.1905  2.1905  2.1905   
97  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225   
98  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023   
99  1.9597  1.9597  1.9597  1.9597  1.9487  1.9487  1.9487  1.9487  1.9487   

         9  ...     991     992     993     994     995     996     997  \
0   1.9328  ...  2.2271  2.2271  2.2271  2.2271  2.2271  2.2271  2.2271   
1   2.2271  ...  2.9866  2.9866  2.9866  2.9866  2.9866  2.9866  2.9866   
2   3.0000  ...  2.6374  2.6374  2.6374  2.6374  2.6374  2.6374  2.6374   
3   2.6374  ...  1.9463  1.9463  1.9463  1.9463  1.9463  1.9463  1.9280   
4   1.9280  ...  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.9963  ...  2.1905  2.1905  2.1905  2.1905  2.1905  2.1905  2.1905   
96  2.1905  ...  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225   
97  2.4225  ...  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023   
98  2.9023  ...  1.9597  1.9597  1.9597  1.9597  1.9597  1.9597  1.9597   
99  1.9487  ...  2.6874  2.6874  2.6874  2.6874  2.6874  2.6874  2.6874   

       998     999                       Status  
0   2.2271  2.2271  1.3_Outer_Bearing_Unhealthy  
1   2.9866  2.9866  1.3_Outer_Bearing_Unhealthy  
2   2.6374  2.6374  1.3_Outer_Bearing_Unhealthy  
3   1.9280  1.9280  1.3_Outer_Bearing_Unhealthy  
4   2.4225  2.4225  1.3_Outer_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.1905  2.1905  1.3_Outer_Bearing_Unhealthy  
96  2.4225  2.4225  1.3_Outer_Bearing_Unhealthy  
97  2.9023  2.9023  1.3_Outer_Bearing_Unhealthy  
98  1.9597  1.9597  1.3_Outer_Bearing_Unhealthy  
99  2.6874  2.7656  1.3_Outer_Bearing_Unhealthy  

[100 rows x 1001 columns]

## 1.5mm-bearing-fault

In [57]:
# 1.5inner-100watt
inner_15_100watt = pd.read_csv('1.5inner-100watt.csv')

# 1.5 outer-100watt
outer_15_100watt = pd.read_csv('1.5outer-100watt.csv')

### Drop the columns and selecting the Current-A column from 1.5inner-100watt and 1.5outer-100watt 

In [58]:
# select Current-A from 1.5outer_100watt
current_A_15inner_100watt = inner_15_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_15inner_100watt

Current-A
0           2.4225
1           2.4225
2           2.4225
3           2.4225
4           2.4225
...            ...
131173      2.0098
131174      2.0098
131175      2.0098
131176      2.0098
131177      2.0098

[131178 rows x 1 columns]

In [59]:
current_A_15inner_100watt_100K = current_A_15inner_100watt[0:100000]
current_A_15inner_100watt_100K

Current-A
0          2.4225
1          2.4225
2          2.4225
3          2.4225
4          2.4225
...           ...
99995      1.9414
99996      1.9414
99997      1.9414
99998      1.9414
99999      1.9414

[100000 rows x 1 columns]

In [60]:
r100_c1k_current_A_15inner_100watt = current_A_15inner_100watt_100K.values.reshape(100,1000)
r100_c1k_current_A_15inner_100watt

array([[2.4225, 2.4225, 2.4225, ..., 2.9512, 2.9512, 2.9512],
       [2.9512, 2.9512, 2.9512, ..., 1.9219, 1.9219, 1.9219],
       [1.9219, 1.9219, 1.9219, ..., 2.7021, 2.7021, 2.7021],
       ...,
       [2.011 , 2.011 , 2.011 , ..., 2.9023, 2.9023, 2.9023],
       [2.9023, 2.9023, 2.9023, ..., 2.6618, 2.6618, 2.63  ],
       [2.63  , 2.63  , 2.63  , ..., 1.9414, 1.9414, 1.9414]])

In [61]:
df_current_A_15inner_100watt = pd.DataFrame(r100_c1k_current_A_15inner_100watt)

In [62]:
df_current_A_15inner_100watt['Status'] = '1.5_Inner_Bearing_Unhealthy'

In [63]:
df_current_A_15inner_100watt

0       1       2       3       4       5       6       7       8  \
0   2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225   
1   2.9512  2.9512  2.9512  2.9512  2.9512  2.9512  2.9512  2.9512  2.9512   
2   1.9219  1.9219  1.9219  1.9219  1.9219  1.9219  1.9219  1.9219  1.9219   
3   2.7021  2.7021  2.7021  2.7021  2.7021  2.7021  2.7021  2.7021  2.7021   
4   2.7009  2.7009  2.7009  2.7009  2.7009  2.7009  2.7009  2.7009  2.7009   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084   
96  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275   
97  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110   
98  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023   
99  2.6300  2.6300  2.6300  2.6300  2.6300  2.6300  2.6300  2.6300  2.6300   

         9  ...     991     992     993     994     995     996     997  \
0   2.4225  ...  2.9853  2.9512  2.9512  2.9512  2.9512  2.9512  2.9512   
1   2.9512  ...  1.9219  1.9219  1.9219  1.9219  1.9219  1.9219  1.9219   
2   1.9219  ...  2.7021  2.7021  2.7021  2.7021  2.7021  2.7021  2.7021   
3   2.7021  ...  2.7485  2.7485  2.7485  2.7485  2.7009  2.7009  2.7009   
4   2.7009  ...  1.9988  1.9988  1.9988  1.9988  1.9988  1.9988  1.9988   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.9084  ...  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275   
96  2.5275  ...  1.9744  1.9744  1.9744  1.9744  1.9744  1.9744  1.9744   
97  2.0110  ...  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023   
98  2.9023  ...  2.6618  2.6618  2.6618  2.6618  2.6618  2.6618  2.6618   
99  2.6300  ...  1.9414  1.9414  1.9414  1.9414  1.9414  1.9414  1.9414   

       998     999                       Status  
0   2.9512  2.9512  1.5_Inner_Bearing_Unhealthy  
1   1.9219  1.9219  1.5_Inner_Bearing_Unhealthy  
2   2.7021  2.7021  1.5_Inner_Bearing_Unhealthy  
3   2.7009  2.7009  1.5_Inner_Bearing_Unhealthy  
4   1.9988  1.9988  1.5_Inner_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.5275  2.5275  1.5_Inner_Bearing_Unhealthy  
96  1.9744  1.9744  1.5_Inner_Bearing_Unhealthy  
97  2.9023  2.9023  1.5_Inner_Bearing_Unhealthy  
98  2.6618  2.6300  1.5_Inner_Bearing_Unhealthy  
99  1.9414  1.9414  1.5_Inner_Bearing_Unhealthy  

[100 rows x 1001 columns]

In [64]:
outer_15_100watt.head()

Time Stamp   Current-A   Current-B   Current-C
0   14:44:14      2.6642      3.0855      1.8217
1   14:44:14      2.6642      3.0855      1.8217
2   14:44:14      2.6642      3.0855      1.8217
3   14:44:14      2.6642      3.0855      1.8217
4   14:44:14      2.6642      3.0855      1.8217

In [65]:
# select Current-A from 1.5outer_100watt
current_A_15outer_100watt = inner_15_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_15outer_100watt

Current-A
0           2.4225
1           2.4225
2           2.4225
3           2.4225
4           2.4225
...            ...
131173      2.0098
131174      2.0098
131175      2.0098
131176      2.0098
131177      2.0098

[131178 rows x 1 columns]

In [66]:
current_A_15outer_100watt_100K = current_A_15outer_100watt[0:100000]
current_A_15outer_100watt_100K

Current-A
0          2.4225
1          2.4225
2          2.4225
3          2.4225
4          2.4225
...           ...
99995      1.9414
99996      1.9414
99997      1.9414
99998      1.9414
99999      1.9414

[100000 rows x 1 columns]

In [67]:
r100_c1k_current_A_15outer_100watt = current_A_15outer_100watt_100K.values.reshape(100,1000)
r100_c1k_current_A_15outer_100watt

array([[2.4225, 2.4225, 2.4225, ..., 2.9512, 2.9512, 2.9512],
       [2.9512, 2.9512, 2.9512, ..., 1.9219, 1.9219, 1.9219],
       [1.9219, 1.9219, 1.9219, ..., 2.7021, 2.7021, 2.7021],
       ...,
       [2.011 , 2.011 , 2.011 , ..., 2.9023, 2.9023, 2.9023],
       [2.9023, 2.9023, 2.9023, ..., 2.6618, 2.6618, 2.63  ],
       [2.63  , 2.63  , 2.63  , ..., 1.9414, 1.9414, 1.9414]])

In [68]:
df_current_A_15outer_100watt = pd.DataFrame(r100_c1k_current_A_15outer_100watt)

In [69]:
df_current_A_15outer_100watt['Status'] = '1.5_Outer_Bearing_Unhealthy'

In [70]:
df_current_A_15outer_100watt

0       1       2       3       4       5       6       7       8  \
0   2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225  2.4225   
1   2.9512  2.9512  2.9512  2.9512  2.9512  2.9512  2.9512  2.9512  2.9512   
2   1.9219  1.9219  1.9219  1.9219  1.9219  1.9219  1.9219  1.9219  1.9219   
3   2.7021  2.7021  2.7021  2.7021  2.7021  2.7021  2.7021  2.7021  2.7021   
4   2.7009  2.7009  2.7009  2.7009  2.7009  2.7009  2.7009  2.7009  2.7009   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084  2.9084   
96  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275   
97  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110  2.0110   
98  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023   
99  2.6300  2.6300  2.6300  2.6300  2.6300  2.6300  2.6300  2.6300  2.6300   

         9  ...     991     992     993     994     995     996     997  \
0   2.4225  ...  2.9853  2.9512  2.9512  2.9512  2.9512  2.9512  2.9512   
1   2.9512  ...  1.9219  1.9219  1.9219  1.9219  1.9219  1.9219  1.9219   
2   1.9219  ...  2.7021  2.7021  2.7021  2.7021  2.7021  2.7021  2.7021   
3   2.7021  ...  2.7485  2.7485  2.7485  2.7485  2.7009  2.7009  2.7009   
4   2.7009  ...  1.9988  1.9988  1.9988  1.9988  1.9988  1.9988  1.9988   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.9084  ...  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275  2.5275   
96  2.5275  ...  1.9744  1.9744  1.9744  1.9744  1.9744  1.9744  1.9744   
97  2.0110  ...  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023  2.9023   
98  2.9023  ...  2.6618  2.6618  2.6618  2.6618  2.6618  2.6618  2.6618   
99  2.6300  ...  1.9414  1.9414  1.9414  1.9414  1.9414  1.9414  1.9414   

       998     999                       Status  
0   2.9512  2.9512  1.5_Outer_Bearing_Unhealthy  
1   1.9219  1.9219  1.5_Outer_Bearing_Unhealthy  
2   2.7021  2.7021  1.5_Outer_Bearing_Unhealthy  
3   2.7009  2.7009  1.5_Outer_Bearing_Unhealthy  
4   1.9988  1.9988  1.5_Outer_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.5275  2.5275  1.5_Outer_Bearing_Unhealthy  
96  1.9744  1.9744  1.5_Outer_Bearing_Unhealthy  
97  2.9023  2.9023  1.5_Outer_Bearing_Unhealthy  
98  2.6618  2.6300  1.5_Outer_Bearing_Unhealthy  
99  1.9414  1.9414  1.5_Outer_Bearing_Unhealthy  

[100 rows x 1001 columns]

## 1.7mm-bearing-fault

In [71]:
# 1.7inner-100watt
inner_17_100watt = pd.read_csv('1.7inner-100watt.csv')

# 1.7outer-100watt
outer_17_100watt = pd.read_csv('1.7outer-100watt.csv')

### Drop the columns and selecting the Current-A column from 1.7inner-100watt and 1.7outer-100watt 

In [72]:
# select Current-A from 1.7outer_100watt
current_A_17inner_100watt = inner_17_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_17inner_100watt

Current-A
0           2.9866
1           2.9866
2           2.9866
3           2.9866
4           2.9866
...            ...
138222      2.9475
138223      2.9475
138224      2.9475
138225      2.9475
138226      2.9475

[138227 rows x 1 columns]

In [73]:
current_A_17inner_100watt_100K = current_A_17inner_100watt[0:100000]
current_A_17inner_100watt_100K

Current-A
0          2.9866
1          2.9866
2          2.9866
3          2.9866
4          2.9866
...           ...
99995      2.3602
99996      2.3602
99997      2.3602
99998      2.3602
99999      2.3602

[100000 rows x 1 columns]

In [74]:
r100_c1k_current_A_17inner_100watt = current_A_17inner_100watt_100K.values.reshape(100,1000)
r100_c1k_current_A_17inner_100watt

array([[2.9866, 2.9866, 2.9866, ..., 2.464 , 2.464 , 2.464 ],
       [2.464 , 2.464 , 2.5531, ..., 2.0794, 2.0794, 2.0794],
       [2.0794, 2.0794, 2.0794, ..., 3.0415, 3.0415, 3.0415],
       ...,
       [2.0415, 2.0415, 2.0415, ..., 2.265 , 2.265 , 2.265 ],
       [2.265 , 2.265 , 2.265 , ..., 3.0171, 3.0171, 3.0171],
       [3.0171, 3.0171, 3.0171, ..., 2.3602, 2.3602, 2.3602]])

In [75]:
df_current_A_17inner_100watt = pd.DataFrame(r100_c1k_current_A_17inner_100watt)

In [76]:
df_current_A_17inner_100watt['Status'] = '1.7_Inner_Bearing_Unhealthy'

In [77]:
df_current_A_17inner_100watt

0       1       2       3       4       5       6       7       8  \
0   2.9866  2.9866  2.9866  2.9866  2.9866  2.9866  2.9866  2.9866  2.9866   
1   2.4640  2.4640  2.5531  2.5531  2.5531  2.5531  2.5531  2.5531  2.5531   
2   2.0794  2.0794  2.0794  2.0794  2.0794  2.0794  2.0794  2.0794  2.0794   
3   3.0415  3.0415  3.0415  3.0415  3.0415  3.0415  3.0415  3.0415  3.0415   
4   2.0610  2.0610  2.0610  2.0610  2.0610  2.0610  2.0610  2.0610  2.0610   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.7338  2.7338  2.7338  2.7338  2.7338  2.7338  2.7338  2.7338  2.7338   
96  2.8303  2.8303  2.8303  2.8303  2.8303  2.8303  2.8303  2.8303  2.8303   
97  2.0415  2.0415  2.0415  2.0415  2.0415  2.0415  2.0415  2.0415  2.0415   
98  2.2650  2.2650  2.2650  2.2650  2.2650  2.2650  2.2650  2.2650  2.2650   
99  3.0171  3.0171  3.0171  3.0171  3.0171  3.0171  3.0171  3.0171  3.0171   

         9  ...     991     992     993     994     995     996     997  \
0   2.9866  ...  2.4640  2.4640  2.4640  2.4640  2.4640  2.4640  2.4640   
1   2.5531  ...  2.0794  2.0794  2.0794  2.0794  2.0794  2.0794  2.0794   
2   2.0794  ...  3.0415  3.0415  3.0415  3.0415  3.0415  3.0415  3.0415   
3   3.0562  ...  2.0610  2.0610  2.0610  2.0610  2.0610  2.0610  2.0610   
4   2.0610  ...  2.6520  2.6520  2.6520  2.6520  2.6520  2.6520  2.6520   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.7338  ...  2.8303  2.8303  2.8303  2.8303  2.8303  2.8303  2.8303   
96  2.8303  ...  2.0415  2.0415  2.0415  2.0415  2.0415  2.0415  2.0415   
97  2.0415  ...  2.4066  2.4066  2.4066  2.2650  2.2650  2.2650  2.2650   
98  2.2650  ...  3.0171  3.0171  3.0171  3.0171  3.0171  3.0171  3.0171   
99  3.0171  ...  2.3602  2.3602  2.3602  2.3602  2.3602  2.3602  2.3602   

       998     999                       Status  
0   2.4640  2.4640  1.7_Inner_Bearing_Unhealthy  
1   2.0794  2.0794  1.7_Inner_Bearing_Unhealthy  
2   3.0415  3.0415  1.7_Inner_Bearing_Unhealthy  
3   2.0610  2.0610  1.7_Inner_Bearing_Unhealthy  
4   2.6520  2.6520  1.7_Inner_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.8303  2.8303  1.7_Inner_Bearing_Unhealthy  
96  2.0415  2.0415  1.7_Inner_Bearing_Unhealthy  
97  2.2650  2.2650  1.7_Inner_Bearing_Unhealthy  
98  3.0171  3.0171  1.7_Inner_Bearing_Unhealthy  
99  2.3602  2.3602  1.7_Inner_Bearing_Unhealthy  

[100 rows x 1001 columns]

In [78]:
outer_17_100watt.head()

Time Stamp   Current-A   Current-B   Current-C
0   15:46:15      2.5055       3.011      2.0256
1   15:46:15      2.5055       3.011      2.0256
2   15:46:15      2.5055       3.011      2.0256
3   15:46:15      2.5055       3.011      2.0256
4   15:46:15      2.5055       3.011      2.0256

In [79]:
# select Current-A from 1.5outer_100watt
current_A_17outer_100watt = outer_17_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_17outer_100watt

Current-A
0           2.5055
1           2.5055
2           2.5055
3           2.5055
4           2.5055
...            ...
136172      2.3748
136173      2.3748
136174      2.3748
136175      2.3748
136176      2.3748

[136177 rows x 1 columns]

In [80]:
current_A_17outer_100watt_100K = current_A_17outer_100watt[0:100000]
current_A_17outer_100watt_100K

Current-A
0          2.5055
1          2.5055
2          2.5055
3          2.5055
4          2.5055
...           ...
99995      1.9915
99996      1.9915
99997      1.9915
99998      1.9915
99999      1.9915

[100000 rows x 1 columns]

In [81]:
r100_c1k_current_A_17outer_100watt = current_A_17outer_100watt_100K.values.reshape(100,1000)
r100_c1k_current_A_17outer_100watt

array([[2.5055, 2.5055, 2.5055, ..., 1.9072, 1.9072, 1.9072],
       [1.9194, 1.9194, 1.9194, ..., 1.9365, 1.9365, 1.9365],
       [1.9365, 1.9365, 1.9365, ..., 1.9231, 1.9231, 1.9231],
       ...,
       [1.9927, 1.9927, 1.9927, ..., 2.8999, 2.8999, 2.8999],
       [2.8999, 2.8999, 2.8999, ..., 2.5653, 2.5653, 2.5653],
       [2.5653, 2.5653, 2.525 , ..., 1.9915, 1.9915, 1.9915]])

In [82]:
df_current_A_17outer_100watt = pd.DataFrame(r100_c1k_current_A_17outer_100watt )

In [83]:
df_current_A_17outer_100watt['Status'] = '1.7_Outer_Bearing_Unhealthy'

In [84]:
df_current_A_17outer_100watt

0       1       2       3       4       5       6       7       8  \
0   2.5055  2.5055  2.5055  2.5055  2.5055  2.5055  2.5055  2.5055  2.5055   
1   1.9194  1.9194  1.9194  1.9194  1.9194  1.9194  1.9194  1.9194  1.9194   
2   1.9365  1.9365  1.9365  1.9365  1.9365  1.9365  1.9365  1.9365  1.9365   
3   1.9231  1.9231  1.9231  1.9231  1.9231  1.9231  1.9231  1.9231  1.9231   
4   1.9341  1.9341  1.9341  1.9341  1.9341  1.9341  1.9341  1.9341  1.9341   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.6813  2.6813  2.6813  2.6813  2.6813  2.6813  2.6813  2.6813  2.6813   
96  2.6654  2.6654  2.6654  2.6654  2.6654  2.6654  2.6654  2.6654  2.6654   
97  1.9927  1.9927  1.9927  1.9927  1.9927  1.9927  1.9927  1.9927  1.9927   
98  2.8999  2.8999  2.8999  2.8999  2.8999  2.8999  2.8999  2.8999  2.8999   
99  2.5653  2.5653  2.5250  2.5250  2.5250  2.5250  2.5250  2.5250  2.5250   

         9  ...     991     992     993     994     995     996     997  \
0   2.5055  ...  1.9072  1.9072  1.9072  1.9072  1.9072  1.9072  1.9072   
1   1.9194  ...  1.9365  1.9365  1.9365  1.9365  1.9365  1.9365  1.9365   
2   1.9365  ...  1.9231  1.9231  1.9231  1.9231  1.9231  1.9231  1.9231   
3   1.9231  ...  1.9328  1.9341  1.9341  1.9341  1.9341  1.9341  1.9341   
4   1.9341  ...  1.9377  1.9377  1.9377  1.9377  1.9377  1.9377  1.9377   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.6813  ...  2.6654  2.6654  2.6654  2.6654  2.6654  2.6654  2.6654   
96  2.6654  ...  1.9927  1.9927  1.9927  1.9927  1.9927  1.9927  1.9927   
97  2.0110  ...  2.8999  2.8999  2.8999  2.8999  2.8999  2.8999  2.8999   
98  2.8999  ...  2.5653  2.5653  2.5653  2.5653  2.5653  2.5653  2.5653   
99  2.5250  ...  1.9915  1.9915  1.9915  1.9915  1.9915  1.9915  1.9915   

       998     999                       Status  
0   1.9072  1.9072  1.7_Outer_Bearing_Unhealthy  
1   1.9365  1.9365  1.7_Outer_Bearing_Unhealthy  
2   1.9231  1.9231  1.7_Outer_Bearing_Unhealthy  
3   1.9341  1.9341  1.7_Outer_Bearing_Unhealthy  
4   1.9377  1.9377  1.7_Outer_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.6654  2.6654  1.7_Outer_Bearing_Unhealthy  
96  1.9927  1.9927  1.7_Outer_Bearing_Unhealthy  
97  2.8999  2.8999  1.7_Outer_Bearing_Unhealthy  
98  2.5653  2.5653  1.7_Outer_Bearing_Unhealthy  
99  1.9915  1.9915  1.7_Outer_Bearing_Unhealthy  

[100 rows x 1001 columns]

## 12-4mm-broken-rotor-bar-fault

In [85]:
# BRB-12-4-100watt
BRB_12_4_100watt = pd.read_csv('BRB-12-4-100watt.csv')

## Drop the columns and selecting the Current-A column from current-12-4mm-broken-rotor-bar-fault 

In [86]:
# select Current-A from BRB_12_4_100watt
current_A_BRB_12_4_100watt = BRB_12_4_100watt.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_BRB_12_4_100watt

Current-A
0           3.0037
1           3.0037
2           3.0037
3           3.0037
4           2.9951
...            ...
139858         NaN
139859         NaN
139860         NaN
139861         NaN
139862         NaN

[139863 rows x 1 columns]

In [87]:
current_A_BRB_12_4_100watt_100K = current_A_BRB_12_4_100watt[0:100000]
current_A_BRB_12_4_100watt_100K

Current-A
0          3.0037
1          3.0037
2          3.0037
3          3.0037
4          2.9951
...           ...
99995      2.0989
99996      2.0989
99997      2.0989
99998      2.0989
99999      2.0989

[100000 rows x 1 columns]

In [88]:
r100_c1k_current_A_BRB_12_4_100watt = current_A_BRB_12_4_100watt_100K.values.reshape(100,1000)
r100_c1k_current_A_BRB_12_4_100watt

array([[3.0037, 3.0037, 3.0037, ..., 3.0842, 3.0842, 3.0842],
       [3.0842, 3.0842, 3.0842, ..., 2.0476, 2.0476, 2.0476],
       [2.0476, 2.0476, 2.0476, ..., 2.5946, 2.5946, 2.5946],
       ...,
       [2.7509, 2.7509, 2.7509, ..., 2.9292, 2.9292, 2.9292],
       [2.906 , 2.906 , 2.906 , ..., 2.1245, 2.1245, 2.1245],
       [2.1245, 2.1245, 2.1245, ..., 2.0989, 2.0989, 2.0989]])

In [89]:
df_current_A_BRB_12_4_100watt = pd.DataFrame(r100_c1k_current_A_BRB_12_4_100watt)

In [90]:
df_current_A_BRB_12_4_100watt['Status'] = 'BRB_rotor_unhealthy'

In [91]:
df_current_A_BRB_12_4_100watt

0       1       2       3       4       5       6       7       8  \
0   3.0037  3.0037  3.0037  3.0037  2.9951  2.9951  2.9951  2.9951  2.9951   
1   3.0842  3.0842  3.0842  3.0842  3.0842  3.0842  3.0842  3.0647  3.0647   
2   2.0476  2.0476  2.0476  2.0476  2.0476  2.0476  2.0476  2.0476  2.0476   
3   2.5946  2.5946  2.6581  2.6581  2.6581  2.6581  2.6581  2.6581  2.6581   
4   2.7546  2.7546  2.7546  2.7546  2.7546  2.7546  2.7546  2.7546  2.7546   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.4420  2.4420  2.4420  2.4420  2.4420  2.4420  2.4420  2.4420  2.4420   
96  1.9927  1.9927  1.9927  1.9927  1.9927  1.9927  1.9927  1.9927  1.9927   
97  2.7509  2.7509  2.7509  2.7509  2.7509  2.7509  2.7509  2.7509  2.7509   
98  2.9060  2.9060  2.9060  2.9060  2.9060  2.9060  2.9060  2.9060  2.9060   
99  2.1245  2.1245  2.1245  2.1245  2.1245  2.1245  2.1245  2.1245  2.1245   

         9  ...     991     992     993     994     995     996     997  \
0   2.9951  ...  3.0842  3.0842  3.0842  3.0842  3.0842  3.0842  3.0842   
1   3.0647  ...  2.0476  2.0476  2.0476  2.0476  2.0476  2.0476  2.0476   
2   2.0476  ...  2.5946  2.5946  2.5946  2.5946  2.5946  2.5946  2.5946   
3   2.6581  ...  2.7546  2.7546  2.7546  2.7546  2.7546  2.7546  2.7546   
4   2.7546  ...  1.9902  1.9902  1.9902  1.9902  1.9902  1.9902  1.9902   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.4420  ...  1.9780  1.9780  1.9780  1.9780  1.9780  1.9780  1.9780   
96  1.9927  ...  2.7509  2.7509  2.7509  2.7509  2.7509  2.7509  2.7509   
97  2.7509  ...  2.9292  2.9292  2.9292  2.9292  2.9292  2.9292  2.9292   
98  2.9060  ...  2.1245  2.1245  2.1245  2.1245  2.1245  2.1245  2.1245   
99  2.1245  ...  2.0989  2.0989  2.0989  2.0989  2.0989  2.0989  2.0989   

       998     999               Status  
0   3.0842  3.0842  BRB_rotor_unhealthy  
1   2.0476  2.0476  BRB_rotor_unhealthy  
2   2.5946  2.5946  BRB_rotor_unhealthy  
3   2.7546  2.7546  BRB_rotor_unhealthy  
4   1.9902  1.9902  BRB_rotor_unhealthy  
..     ...     ...                  ...  
95  1.9927  1.9927  BRB_rotor_unhealthy  
96  2.7509  2.7509  BRB_rotor_unhealthy  
97  2.9292  2.9292  BRB_rotor_unhealthy  
98  2.1245  2.1245  BRB_rotor_unhealthy  
99  2.0989  2.0989  BRB_rotor_unhealthy  

[100 rows x 1001 columns]

## current-healthy-motor

In [92]:
# 3-Phase-current-healthy-motor

current_healthy_motor = pd.read_csv('healthy.csv')

## Drop the columns and selecting the Current-A column from  current-healthy-motor 

In [93]:
# select Current-A from BRB_12_4_100watt
current_A_current_healthy_motor = current_healthy_motor.drop(['Time Stamp',' Current-B',' Current-C'],axis=1)
current_A_current_healthy_motor

Current-A
0           2.4908
1           2.4908
2           2.4908
3           2.4908
4           2.4908
...            ...
116970      2.5494
116971      2.5494
116972      2.5494
116973      2.5494
116974      2.5494

[116975 rows x 1 columns]

In [94]:
current_A_current_healthy_motor_100K = current_A_current_healthy_motor[0:100000]
current_A_current_healthy_motor_100K

Current-A
0          2.4908
1          2.4908
2          2.4908
3          2.4908
4          2.4908
...           ...
99995      2.2894
99996      2.2894
99997      2.2894
99998      2.2894
99999      2.2894

[100000 rows x 1 columns]

In [95]:
r100_c1k_current_A_current_healthy_motor = current_A_current_healthy_motor_100K.values.reshape(100,1000)
r100_c1k_current_A_current_healthy_motor

array([[2.4908, 2.4908, 2.4908, ..., 2.6667, 2.6667, 2.7558],
       [2.7558, 2.7558, 2.7558, ..., 2.6728, 2.6728, 2.6728],
       [2.6728, 2.6728, 2.6728, ..., 2.6361, 2.6361, 2.6361],
       ...,
       [2.3065, 2.3065, 2.3065, ..., 2.2552, 2.2552, 2.2552],
       [2.2552, 2.2552, 2.2552, ..., 2.2466, 2.2466, 2.2466],
       [2.2479, 2.2479, 2.2479, ..., 2.2894, 2.2894, 2.2894]])

In [96]:
df_current_A_current_healthy_motor = pd.DataFrame(r100_c1k_current_A_current_healthy_motor)

In [97]:
df_current_A_current_healthy_motor['Status'] = 'Healthy_Motor'

In [98]:
df_current_A_current_healthy_motor

0       1       2       3       4       5       6       7       8  \
0   2.4908  2.4908  2.4908  2.4908  2.4908  2.4908  2.4908  2.4908  2.4908   
1   2.7558  2.7558  2.7558  2.7558  2.7558  2.7558  2.7558  2.7558  2.7558   
2   2.6728  2.6728  2.6728  2.6728  2.6728  2.6728  2.6728  2.7558  2.7558   
3   2.6361  2.6361  2.6361  2.6361  2.6361  2.6361  2.6361  2.6361  2.6361   
4   2.4945  2.4945  2.4945  2.4945  2.4945  2.4945  2.4945  2.4945  2.4945   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.4603  2.4530  2.4530  2.4530  2.4530  2.4530  2.4530  2.4530  2.4530   
96  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712   
97  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065   
98  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552   
99  2.2479  2.2479  2.2479  2.2479  2.2479  2.2479  2.2479  2.2479  2.2479   

         9  ...     991     992     993     994     995     996     997  \
0   2.4908  ...  2.6667  2.6667  2.6667  2.6667  2.6667  2.6667  2.6667   
1   2.7558  ...  2.6728  2.6728  2.6728  2.6728  2.6728  2.6728  2.6728   
2   2.7558  ...  2.5665  2.5665  2.5665  2.5665  2.5665  2.5665  2.6361   
3   2.6361  ...  2.4945  2.4945  2.4945  2.4945  2.4945  2.4945  2.4945   
4   2.4945  ...  2.2625  2.2625  2.2625  2.2625  2.2625  2.2625  2.2625   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.4530  ...  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712   
96  2.3712  ...  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065   
97  2.3065  ...  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552   
98  2.2552  ...  2.2466  2.2466  2.2466  2.2466  2.2466  2.2466  2.2466   
99  2.2479  ...  2.2894  2.2894  2.2894  2.2894  2.2894  2.2894  2.2894   

       998     999         Status  
0   2.6667  2.7558  Healthy_Motor  
1   2.6728  2.6728  Healthy_Motor  
2   2.6361  2.6361  Healthy_Motor  
3   2.4945  2.4945  Healthy_Motor  
4   2.2625  2.2625  Healthy_Motor  
..     ...     ...            ...  
95  2.3712  2.3712  Healthy_Motor  
96  2.3065  2.3065  Healthy_Motor  
97  2.2552  2.2552  Healthy_Motor  
98  2.2466  2.2466  Healthy_Motor  
99  2.2894  2.2894  Healthy_Motor  

[100 rows x 1001 columns]

In [99]:
final_df = pd.concat([

            df_current_A_07inner_100watt,df_current_A_07outer_100watt,
            df_current_A_09inner_100watt,df_current_A_09outer_100watt,
            df_current_A_11inner_100watt,df_current_A_11outer_100watt,
            df_current_A_13inner_100watt,df_current_A_13outer_100watt,
            df_current_A_15inner_100watt,df_current_A_15outer_100watt,
            df_current_A_17inner_100watt,df_current_A_17outer_100watt,
            df_current_A_BRB_12_4_100watt,df_current_A_current_healthy_motor
            ])

In [100]:
final_df

0       1       2       3       4       5       6       7       8  \
0   2.3309  2.3309  2.3309  2.3309  2.3309  2.3309  2.3309  2.3309  2.3309   
1   2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228   
2   2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524   
3   2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111   
4   2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
95  2.4603  2.4530  2.4530  2.4530  2.4530  2.4530  2.4530  2.4530  2.4530   
96  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712   
97  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065   
98  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552   
99  2.2479  2.2479  2.2479  2.2479  2.2479  2.2479  2.2479  2.2479  2.2479   

         9  ...     991     992     993     994     995     996     997  \
0   2.3309  ...  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228  2.7228   
1   2.7228  ...  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524  2.9524   
2   2.9524  ...  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111  2.1111   
3   2.1111  ...  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282  2.1282   
4   2.1282  ...  2.9805  2.9805  2.9805  2.9805  3.0024  3.0024  3.0024   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
95  2.4530  ...  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712  2.3712   
96  2.3712  ...  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065  2.3065   
97  2.3065  ...  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552  2.2552   
98  2.2552  ...  2.2466  2.2466  2.2466  2.2466  2.2466  2.2466  2.2466   
99  2.2479  ...  2.2894  2.2894  2.2894  2.2894  2.2894  2.2894  2.2894   

       998     999                       Status  
0   2.7228  2.7228  0.7_Inner_Bearing_Unhealthy  
1   2.9524  2.9524  0.7_Inner_Bearing_Unhealthy  
2   2.1111  2.1111  0.7_Inner_Bearing_Unhealthy  
3   2.1282  2.1282  0.7_Inner_Bearing_Unhealthy  
4   3.0024  3.0024  0.7_Inner_Bearing_Unhealthy  
..     ...     ...                          ...  
95  2.3712  2.3712                Healthy_Motor  
96  2.3065  2.3065                Healthy_Motor  
97  2.2552  2.2552                Healthy_Motor  
98  2.2466  2.2466                Healthy_Motor  
99  2.2894  2.2894                Healthy_Motor  

[1400 rows x 1001 columns]

In [101]:
final_df.to_csv('motor dataset.csv', index=False, header=False)

In [102]:
data = pd.read_csv('motor dataset.csv')

In [103]:
data.head()

2.3309  2.3309.1  2.3309.2  2.3309.3  2.3309.4  2.3309.5  2.3309.6  \
0  2.7228    2.7228    2.7228    2.7228    2.7228    2.7228    2.7228   
1  2.9524    2.9524    2.9524    2.9524    2.9524    2.9524    2.9524   
2  2.1111    2.1111    2.1111    2.1111    2.1111    2.1111    2.1111   
3  2.1282    2.1282    2.1282    2.1282    2.1282    2.1282    2.1282   
4  3.0024    3.0024    3.0024    3.0024    3.0024    3.0024    3.0024   

   2.3309.7  2.3309.8  2.3309.9  ...  2.7228.4  2.7228.5  2.7228.6  2.7228.7  \
0    2.7228    2.7228    2.7228  ...    2.9524    2.9524    2.9524    2.9524   
1    2.9524    2.9524    2.9524  ...    2.1111    2.1111    2.1111    2.1111   
2    2.1111    2.1111    2.1111  ...    2.1282    2.1282    2.1282    2.1282   
3    2.1282    2.1282    2.1282  ...    2.9805    2.9805    2.9805    2.9805   
4    3.0024    3.0024    3.0024  ...    2.6227    2.6227    2.6227    2.6227   

   2.7228.8  2.7228.9  2.7228.10  2.7228.11  2.7228.12  \
0    2.9524    2.9524     2.9524     2.9524     2.9524   
1    2.1111    2.1111     2.1111     2.1111     2.1111   
2    2.1282    2.1282     2.1282     2.1282     2.1282   
3    3.0024    3.0024     3.0024     3.0024     3.0024   
4    2.6227    2.6227     2.6227     2.6227     2.6227   

   0.7_Inner_Bearing_Unhealthy  
0  0.7_Inner_Bearing_Unhealthy  
1  0.7_Inner_Bearing_Unhealthy  
2  0.7_Inner_Bearing_Unhealthy  
3  0.7_Inner_Bearing_Unhealthy  
4  0.7_Inner_Bearing_Unhealthy  

[5 rows x 1001 columns]

In [109]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import statistics

dataset = pd.read_csv("motor dataset.csv")

X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, 1000].values

x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=0.80, random_state=0)


def find_dis(data1, data2):
    dis = 0
    for x in range(len(data1)):
        dis += np.square(data1[x] - data2[x])
    return np.sqrt(dis)


def get_labels(from_this_list, list2):
    class_labels = []
    for dis in list2:
        for x in range(len(from_this_list)):
            if dis == from_this_list[x][0]:
                class_labels.append(from_this_list[x][1])
    return class_labels


def knn(train_set, test_instance, k):
    dist = []
    for j in range(len(train_set)):
        dist.append([find_dis(test_instance, train_set[j]), y_train[j]])

    distances = []
    for index in range(len(dist)):
        distances.append(dist[index][0])

    distances.sort()
    distances = distances[0:k]
    labels = get_labels(dist, distances)
    return statistics.mode(labels)

pred = []

for i in x_test:
    pred.append(knn(x_train, i, 3))

print(confusion_matrix(pred, y_test))
print('Accuracy Score -> ',accuracy_score(pred, y_test))



[[ 4  1  1  3  0  0  0  4  0  0  2  0  0  0]
 [ 4  5  0  4  1  0  0  0  2  1  0  1  2  0]
 [ 1  1  1  1  0  1  1  2  0  0  1  1  1  0]
 [ 3  0  2  5  0  0  0  0  0  1  0  0  1  0]
 [ 1  1  3  0  2  2  1  1  0  0  0  0  0  3]
 [ 1  0  0  0  6 10  1  0  1  1  0  3  4  1]
 [ 0  0  1  0  2  5  4  0  0  0  0  3  0  1]
 [ 5  1  2  0  4  4  0  7  1  1  2  1  3  0]
 [ 4  4  0  3  3  0  0  2  1 23  1  2  3  1]
 [ 0  0  1  3  0  1  2  1  9  0  0  1  1  0]
 [ 1  0  6  1  0  0  0  0  0  0 11  0  0  0]
 [ 1  0  0  0  4  2  0  1  0  0  0  4  2  1]
 [ 3  2  0  0  3  0  1  0  0  0  0  0  4  0]
 [ 0  0  2  0  0  0  3  0  0  0  0  3  2 10]]
Accuracy Score ->  0.24285714285714285
